---
micronaut:
  server:
    cors:
      enabled: true
      configurations:
        allowedOrigins:
          - http://localhost:3000
          - localhost:3000
          - http://127.0.0.1:3000
---
micronaut:
  security:
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${UNITY_SIGNATURE_SECRET:123456789012345123456789012345123456789012345123456789012345123456789012345}"'
    redirect:
      login-success: http://localhost:3000
      login-failure: http://localhost:3000/?login-failed=true
      logout: http://localhost:8080